<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ADMINRG-B4GU5HF" failures="0" tests="9" name="com.morningnineam.TEst" time="0.043" errors="1" timestamp="2023-09-09T09:32:35 IST" skipped="5">
  <testcase classname="com.morningnineam.TEst" name="launch" time="0.016"/>
  <testcase classname="com.morningnineam.TEst" name="url" time="0.008"/>
  <testcase classname="com.morningnineam.TEst" name="login" time="0.005"/>
  <testcase classname="com.morningnineam.TEst" name="addtocart" time="0.003">
    <skipped/>
  </testcase> <!-- addtocart -->
  <testcase classname="com.morningnineam.TEst" name="addtocart" time="0.004">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at com.morningnineam.TEst.addtocart(TEst.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- addtocart -->
  <testcase classname="com.morningnineam.TEst" name="addtocart" time="0.003">
    <skipped/>
  </testcase> <!-- addtocart -->
  <testcase classname="com.morningnineam.TEst" name="addtocart" time="0.003">
    <skipped/>
  </testcase> <!-- addtocart -->
  <testcase classname="com.morningnineam.TEst" name="payment" time="0.001">
    <skipped/>
  </testcase> <!-- payment -->
  <testcase classname="com.morningnineam.TEst" name="delivery" time="0.000">
    <skipped/>
  </testcase> <!-- delivery -->
</testsuite> <!-- com.morningnineam.TEst -->
